#define LOGIN_REQUEST -58
#define WRONG_CREDENTIAL -59
#define NORMAL_MESSAGE 0
#define SESION_LIST_SEND -67
#define SESSION_JOIN_REQUEST -68
#define FILE_TRANSFER -69
#define SESSION_JOIN_INFORMATION -65
#define USER_SIGNUP -24